### ISSUE TITLE
config as an object (without using as ss as middleware for connect) routes not working properly

### ISSUE THREAD

**Issue by lgubenis** [divshot/superstatic#130]
```
var superstatic = require('superstatic/lib/server');

var spec = {
  gzip: true,
  port: 8315,
  debug: true,
  config: {
    root: './dist',
    routes: {
      '**': './dist/index.html'
    }
  }
};

superstatic(spec).listen();
```

thats my index.js, when i run it with node and access localhost:8315/test there is a 404, where i thought that the index.html is sent,

i also tried things with cwd and other roots but the same thing happens, when i use the divshot.json with that config part everything works as it should, im using the latest version 2.0.0-rc1

**Comment by lgubenis** [comment]
````
var superstatic = require('superstatic/lib/server');

var spec = {
  gzip: true,
  port: 8315,
  debug: true,
  config: {
    root: './dist',
    routes: {
      '**': './dist/index.html'
    }
  },
  errorPage: './dist/index.html'
};

superstatic(spec).listen();
`````
that works

**Comment by scottcorgan** [comment]
Have you tried

```js
routes: {
  '**': 'index.html'
}
```

It uses the app root as the relative path for serving the files.

**Comment by scottcorgan** [comment]
@lgubenis can you confirm if my recommendation above works?

**Comment by lgubenis** [comment]
it works if i am using the divshot.json and running superstatic as cli
but it doesnt work if i use the lib/server from superstatic with it as the config, i need to specify the root folder './dist/index.html' even if i put the root to './dist' or cwd in the options string into ./dist

**Comment by scottcorgan** [comment]
@lgubenis published 2.0.0-rc3 to NPM. Can you try now?

**Comment by scottcorgan** [comment]
BTW, here's an example app I used to test your code: https://cloudup.com/cgap7Q3rbx8

**Comment by lgubenis** [comment]
i will try out now

**Comment by lgubenis** [comment]
its not working

```
var server = require('superstatic/lib/server');

var options = {
  gzip: true,
  port: 8315,
  config: {
    root: './dist',
    routes: {
      '**': 'index.html'
    }
  }
};

server(options).listen(function() {
  console.info('[INFO]', 'running on port:', options.port);
});
```

my folder structure:
```
dist/index.html
index.js
package.json
```

package.json with a script for start which is "node index.js"
running npm start from the same directory

**Comment by lgubenis** [comment]
it displays the index.html but js and css references are not loaded, instead the index.htm is loaded

**Comment by scottcorgan** [comment]
Ah, I see. Yes, that is a different issue altogether. Let me investigate and fix that.

**Comment by lgubenis** [comment]
in my dist, i have a /css folder with a style.css

and in the index.html im referencing to it like this "/css/style.css" with the divshot.json that worked.

**Comment by scottcorgan** [comment]
@lgubenis can you try `rc4`. Should fix things.

**Comment by lgubenis** [comment]
awesome, works like a charm!

**Comment by scottcorgan** [comment]
Appreciate your help is squashing that bug. Look for the `2.0` release next week!
