### ISSUE TITLE
Configuration option to disable automatic removal of trailing slashes

### ISSUE THREAD

**Issue by asmth** [divshot/superstatic#131]
It would be nice to have the option to disable the removal of trailing slashes in urls for dynamic query parameters.

An example Angular UIRouter:

`$stateProvider.state('index', {
      url: '/dashboard/',
      templateUrl: 'app/view/dashboard.html',
      controller: 'controller.dashboard',
});`

`dashboard/?param1=value&param2=value` re-routes to: `dashboard?param1=value&param2=value` 

Which will no longer match the route.

This will allow for dynamic query parameters to be passed to the controller.

The removal of the trailing slash is a nice feature, and works great for most cases - would it be an idea to disable on a route by route basis?

`{
  "name": "app",
  "root": "public",
  "routes": {
    "**": "index.html"
  },
  "clean_urls": true,
  "error_page": "error.html"
  "slashes": ["/dashboard", "/orders"]
}`

**Comment by scottcorgan** [comment]
One of the main reasons we added this feature automatically is that we found that assets referenced in an html file with a relative path weren't resolved by the browser correctly without the slash.

We will keep it on by default, and allow configure similar to clean_urls with a Boolean and a string or array of file path/globs

**Comment by scottcorgan** [comment]
@asmth can you route without the trailing slash in ui router?

**Comment by asmth** [comment]
`dashboard?param1=value&param2=value` doesn't currently route, however `dashboard/?param1=value&param2=value` does.

**Comment by scottcorgan** [comment]
Until this gets in, check this out as a temporary fix: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes

**Comment by marquex** [comment]
+1 for this feature :)

**Comment by mbleigh** [comment]
@scottcorgan didn't you fix the specific issue described in c5581cb4 yesterday?

**Comment by mbleigh** [comment]
We try to be stingy about adding new top-level configuration to `divshot.json` as a matter of API hygiene, so I'm just trying to figure out if there's a way for us to automatically behave in a way that will match user needs.

That being said, this may be worth it. I don't think it needs to be on a per-route basis. If you want trailing slashes or don't want them you should be consistent in your usage. What about a `trailing_slash` option that:

1. When `true` forces trailing slashes on
2. When `false` forces trailing slashes off
3. When `null` behaves as it does today and keeps them for directory indexes but removes them otherwise.

**Comment by marquex** [comment]
@mbleigh 

I think that is a nice solution. I am migrating a site that always added the trailing slash and I am getting the opposite from divshot, so it would be great to have config parameter as the one you said.

Cheers,
Javi

**Comment by martinhendleman** [comment]
+1 .  Would love to see this get rolled out.  I'm trying to solve an SEO problem and this is the missing piece of the puzzle.

**Comment by scottcorgan** [comment]
@marquex any way you can open up a pull request with a failing for this case? Trying to determine what's causing it.
