### ISSUE TITLE
Serve JSON like serving HTML

### ISSUE THREAD

**Issue by pipefishbook** [divshot/superstatic#139]
Hi,

just wondering if there would be a quick way to serve some JSON with superstatic?

e.g. example.com/mydata.json

It might be nice to have a file based API service with divshot too.

**Comment by scottcorgan** [comment]
You should be able to just add json files and they get served like any other file.

What issues are you running into?

**Comment by pipefishbook** [comment]
Ah, it is chrome's redirect to google that was confusing here. indeed, with curl, I can fetch the data.

**Comment by pipefishbook** [comment]
Ok, but I need to add .json? This does not work:

    $.get('/api/messer', function(resp) { console.log(resp) })

**Comment by scottcorgan** [comment]
Ya, add the `.json` extension and all should be fine.
