### ISSUE TITLE
Test on Node 0.12 and io.js

### ISSUE THREAD

**Issue by scottcorgan** [divshot/superstatic#141]

**Comment by rwjblue** [comment]
Also iojs, if you don't mind...

**Comment by kevinchau** [comment]
@rwjblue we were just talking about that. Reading our minds :)

**Comment by scottcorgan** [comment]
I'll add badges to the readme as well

**Comment by scottcorgan** [comment]
Tests on

* 0.10
* 0.12
* iojs
