### ISSUE TITLE
Rewrite for WebP

### ISSUE THREAD

**Issue by JosefJezek** [divshot/superstatic#144]
Could you explain how to make rewrite for WebP?

See http://stefanimhoff.de/2014/gulp-tutorial-15-performance-improvements-webp-gzip/

**Comment by scottcorgan** [comment]
What do you mean by "rewrite for WebP"?

Custom route? Clean urls?

**Comment by JosefJezek** [comment]
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP_ACCEPT} image/webp
  RewriteCond %{DOCUMENT_ROOT}/$1.webp -f
  RewriteRule (.+)\.(jpe?g|png)$ $1.webp [T=image/webp,E=accept:1]
</IfModule>

<IfModule mod_headers.c>
  Header append Vary Accept env=REDIRECT_accept
</IfModule>

AddType image/webp .webp
```

**Comment by scottcorgan** [comment]
Does this relate to giving the server the ability to serve webp formatted images?

**Comment by jzorn** [comment]
As far as I understand it, this is about automatically serving the WebP version of a requested image if the client accepts it.

The client requests a picture (example.png), the server checks if the client accepts image/webp and rewrites the request to server the webp version of it...

**Comment by JosefJezek** [comment]
Yes ;-)

**Comment by jzorn** [comment]
I am afraid that is not a core feature of superstatic, you probably have to implement your own middleware to do this.

**Comment by scottcorgan** [comment]
This sounds like a great idea for a Superstatic service. Would you want to write a middleware or know of any middleware for this?

**Comment by jzorn** [comment]
I might find the time to implement something on the weekend.

**Comment by jzorn** [comment]
This one even generates the images on the fly. Nice.

**Comment by scottcorgan** [comment]
Ya, I'm not sure generating the images on the fly is ideal, but this could be a starting point.

**Comment by scottcorgan** [comment]
@jzorn Any luck with this?

**Comment by jzorn** [comment]
Yeah I am working on it - I created an express middleware, but I struggle turning it into a superstatic service. Any advise on that?

**Comment by jzorn** [comment]
Okay, here is my current WIP: [jzorn/rewrite-webp](/jzorn/rewrite-webp) - suggestions welcome. Right now, it's just serving an existing webp version of an image if the client supports it.

**Comment by scottcorgan** [comment]
@jzorn looks really good.

Can you get some tests written for it?

Would love to get this as a service for Superstatic, so if that's something you're interested in, renaming it to `superstatic-webp` would be helpful to keep it consistent with the other services. Once it's approved as a service by us, we can then launch it to work on Divshot Hosting.

If you don't want to rename it, you can create another middleware that wraps this middleware and name that new middleware `superstatic-webp`.

Let me know if you need help.

**Comment by jzorn** [comment]
Sure will do!

**Comment by scottcorgan** [comment]
@jzorn any update on this? Going to close the issue. Reopen if it's still something that you'd like to move forward with.
