### ISSUE TITLE
External Redirects

### ISSUE THREAD

**Issue by kevinchau** [divshot/superstatic#146]
```
"redirects": {
    "/carter/redirect/test": "http://google.com"
}
```

Should just go to google.com, instead it does this: http://domain.divshot.io/http:/google.com

**Comment by wronco** [comment]
I'm unable to get a redirect to an https external url to work. I've worked around this issue for now by just redirecting to the http version of the page, but it would be awesome to be able to specify an https url.

**Comment by scottcorgan** [comment]
@wronco This if fixed in https://github.com/divshot/redirects/commit/b69d39dcdfed45c73ae688a93ebf53ea9e150188

It's been deployed and is live. Reinstall the cli with `npm install divshot-cli -g` to get the patch locally.
