### ISSUE TITLE
Caching issues on 2.1.0

### ISSUE THREAD

**Issue by epicbagel** [divshot/superstatic#151]
When creating a server via the API, it appears all files are being cached despite any configuration setting (set via .json or the options object). 

This appears to be a regression from 2.0.2, as that handles the disabling of caching correctly. On 2.0.2:

    var superstatic = require('superstatic/lib/server')
    var app = superstatic({
        //config: "divshot-localdev.json",
        config: {
            root: "./build/",
            debug: true,
            cache_control: {
                "**": false
            },
            routes: {
                "**": "index.html"
            }
        },
        port: 5001
    }).listen() 

On 2.1.0 I was using the same options object, but used the new import changes:

    var superstatic = require('superstatic')
    app = superstatic.server({
    ....

**Comment by scottcorgan** [comment]
@epicbagel can you try setting `cache_control` to `false` instead of using an glob object. 

```js
var superstatic = require('superstatic/lib/server')
var app = superstatic({
    //config: "divshot-localdev.json",
    config: {
        root: "./build/",
        debug: true,
        cache_control: false,
        routes: {
            "**": "index.html"
        }
    },
    port: 5001
}).listen() 
```

If that works I have idea of where it wrong.

**Comment by epicbagel** [comment]
@scottcorgan didn't work I'm afraid. Tried cache_control: false on 2.1.0 and it still cached the assets. Had to clear file cache in the browser to see changes come through. 2.0.2 works fine.

**Comment by scottcorgan** [comment]
Can you post your response headers?

**Comment by scottcorgan** [comment]
@epicbagel any luck on getting those response headers?

**Comment by eloyesp** [comment]
response headers extracted from firebug:

```
Connection	keep-alive
Date	Wed, 04 Mar 2015 00:44:17 GMT
Etag	"1B2M2Y8AsgTpgAmY7PhCfg=="

# original cached headers:

Content-Length	751
Content-Type	application/javascript; charset=utf-8
Date	Wed, 04 Mar 2015 00:44:17 GMT
Etag	"1B2M2Y8AsgTpgAmY7PhCfg=="
```

and the cached tab (also in firebug)

```
Data Size	751
Expires	Wed Dec 31 1969 21:00:00 GMT-0300 (ART)
Fetch Count	5
Last Fetched	Tue Mar 03 2015 21:44:18 GMT-0300 (ART)
Last Modified	Tue Mar 03 2015 21:44:17 GMT-0300 (ART)
```

**Comment by eloyesp** [comment]
I'm using the CLI, and I have the same issue. (I was using the `--no-cache` option) but it required always full-refresh. (so not useful for development)

**Comment by scottcorgan** [comment]
@eloyesp Are you referring to the Etag header?

According to your headers, there is no caching happening.

**Comment by eloyesp** [comment]
​No, it is *not* being cached by the browser, it is being cached by the server, it respond with "not changed", when I modify the file.

So, I start the server, browse to the file, then I modify the original file and reload in the browser, but I get a 304 "not modified" response.

**Comment by scottcorgan** [comment]
Yep, it's the Etags. I'll add a flag to turn them off.

**Comment by aj0strow** [comment]
This is beyond frustrating. Let me know if I can help.

**Comment by mbleigh** [comment]
@scottcorgan shouldn't the ETags change whenever file content changes? If the file has changed locally, why would we be sending a 304?

**Comment by scottcorgan** [comment]
We made a decision to keep etag support on for all files. It should now generate a new etag when you change a file, alleviating the headache of the cache issues. Sorry about that!

**Comment by scottcorgan** [comment]
Published as `2.1.3` on NPM

**Comment by richtera** [comment]
I still can't get this to work reliably. Even though the it does generate ETags I have users complaining about getting old versions of our app. I constantly have to tell end users to click Ctrl-R or Cmd-R to get the latest versions of all files. It's gotten a lot worse since ETags were enabled by default.

**Comment by mbleigh** [comment]
@richtera how are you currently deploying Superstatic? Version 4 has a totally rewritten provider system with an improved ETags implementation (but has quite a few breaking changes so isn't a drop-in replacement).

**Comment by richtera** [comment]
I am actually using firebase hosting and it's having the same problems
described here. Unfortunately since divshot has been added to firebase I
see an express server serving up the content, but it's not revealing
whether it's running superstatic, but I think it is.

On Wed, Jan 6, 2016 at 2:25 PM, Michael Bleigh <notifications@github.com>
wrote:

> @richtera <https://github.com/richtera> how are you currently deploying
> Superstatic? Version 4 has a totally rewritten provider system with an
> improved ETags implementation (but has quite a few breaking changes so
> isn't a drop-in replacement).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/superstatic/issues/151#issuecomment-169428904>
> .
>



-- 

Andreas Richter LLC
<http://richtera.org/>
n: *Andreas Richter*
e: andy@richtera.org
c: 215-518-2619
o: 484-238-0538
s: andyxp.richteralsi
gt: andy@richtera.org
g+: google.com/+AndreasRichterLLC
l: linkedin.com/in/richtera <http://www.linkedin.com/in/richtera>
t: @richtera <https://twitter.com/richtera>
a: richtera@me.com
y: richterar66home

**Comment by mbleigh** [comment]
Well then that definitely shouldn't be happening -- are you specifying any `Cache-Control` headers in your `firebase.json`? Are users having the problem minutes, hours, or days after a deploy? Feel free to email firebase-support@google.com with your specific issues, we'd be happy to help.

**Comment by richtera** [comment]
It's ignoring all the Cache-Control headers I have set. It's just not
working for us for some reason.
My firebase.json contains:
```javascript
{
  "firebase": "...",
  "public": "dist",
  "rewrites": [
    {
      "source": "**",
      "destination": "/index.html"
    }
  ],
  "headers": [
    {
      "source" : "**/*.@(eot|otf|ttf|ttc|woff|font.css)",
      "headers" : [
        {
          "key" : "Access-Control-Allow-Origin",
          "value" : "*"
        }
      ]
    },
    {
      "source" : "**/*.@(jpg|jpeg|gif|png)",
      "headers" : [
        {
          "key" : "Cache-Control",
          "value" : "max-age=7200"
        }
      ]
    },
    {
      "source": "/index.html",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "no-cache, no-store, must-revalidate"
        }
      ]
    }
  ]
}
```
But yet my headers contain:
```
HTTP/1.1 200 OK Server: nginx Content-Type: text/html; charset=utf-8
X-Powered-By: Express Cache-Control: max-age=3600
Strict-Transport-Security: max-age=31556926 ETag:
"00a5b748a5ae846bdd3736b917638a8e" Last-Modified: Wed, 06 Jan 2016 17:22:29
GMT Content-Encoding: gzip Content-Length: 1009 Accept-Ranges: bytes Date:
Wed, 06 Jan 2016 19:35:08 GMT Via: 1.1 varnish Connection: keep-alive
X-Served-By: cache-iad2132-IAD X-Cache: MISS X-Cache-Hits: 0 Vary:
Accept-Encoding
```

NOTE: This used to work when attaching the header to the raw file which is
the default redirect for a html5 routing URL.
But even then... it should refresh the files after an hour which is not
happening either. I am not sure if the ETag is just never
changing since there is no real file at the URL.
Thanks
Andy


On Wed, Jan 6, 2016 at 2:32 PM, Michael Bleigh <notifications@github.com>
wrote:

> Well then that definitely shouldn't be happening -- are you specifying any
> Cache-Control headers in your firebase.json? Are users having the problem
> minutes, hours, or days after a deploy? Feel free to email
> firebase-support@google.com with your specific issues, we'd be happy to
> help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/superstatic/issues/151#issuecomment-169433055>
> .
>



-- 

Andreas Richter LLC
<http://richtera.org/>
n: *Andreas Richter*
e: andy@richtera.org
c: 215-518-2619
o: 484-238-0538
s: andyxp.richteralsi
gt: andy@richtera.org
g+: google.com/+AndreasRichterLLC
l: linkedin.com/in/richtera <http://www.linkedin.com/in/richtera>
t: @richtera <https://twitter.com/richtera>
a: richtera@me.com
y: richterar66home

**Comment by jensgeffken** [comment]
caching on png and image files works like charm, css and js files are not all, no idea, can anyone help please ? thanks

**Comment by richtera** [comment]
This is a really old issue. I am no longer using superstatic or firebase hosting.

**Comment by richtera** [comment]
At the time I had to change it so that the html file didn't cache and the js files were hashed. That way changing the html file would require the end user browser to reload the html file and load and cache new js files since they had different hashed names.

**Comment by jensgeffken** [comment]
ok thanks, i am on it :-)

**Comment by chux0519** [comment]
using custom provider can roughly solve the the problem (by removing the `etag` and `last-modified` header).

```javascript
const superstatic = require('superstatic').server
const path = require('path')
const fsProvider = require('superstatic/lib/providers/fs')

// Remove etag, cancel the browser's cache, avoid update issues
function noCacheProvider (options) {
  const handler = fsProvider(options)
  return (req, pathname) => handler(req, pathname).then(res => {
    if (res) { // res can be null
      res.modified = false
      res.etag = false
    }
    return res
  })
}

const config = {
  'rewrites': [
    {'source': '/*', 'destination': 'index.html'}
  ]
}

const port = Number(process.env.PORT) || 8080
const distPath = path.join(__dirname, './dist')

const app = superstatic({
  provider: noCacheProvider({cwd: distPath, ...config}),
  port,
  cwd: distPath,
  config,
  compression: true
})

app.listen(() => {
  console.log(`Serving on port ${port}...`)
})

```
