### ISSUE TITLE
Error when requesting directory

### ISSUE THREAD

**Issue by developit** [divshot/superstatic#152]
When using a completely stock setup (`superstatic.server({})`), requesting a URL that resolves to a directory itself causes an error.  It appears Superstatic attempts to create a read stream for the path, but an error is thrown asynchronously, which causes the process to exit.

Is this a known issue? I searched for a couple hours and couldn't find anything.  Node appears to special-case `error` events - if an `error` handler is present it will call it, otherwise it will throw an exception.  Could this be as simple as adding an `error` handler to the readStream?

**Comment by scottcorgan** [comment]
Does the same thing happen when you use superstatic as a middleware?

**Comment by developit** [comment]
Yes, as well as from the CLI. The only way I have been able to work around this was to define a middleware prior to superstatic that checks `fs.stat()->is directory()` and triggers a 400.

**Comment by developit** [comment]
Wow, thanks for the quick fix Scott.  Got a release version/date in mind?

**Comment by scottcorgan** [comment]
It will be `2.1.1` as soon as the tests pass on Travis.

**Comment by scottcorgan** [comment]
Published
