### ISSUE TITLE
Specific paths / glob patterns not working for clean_urls

### ISSUE THREAD

**Issue by fastdivision** [divshot/superstatic#161]
Superstatic doesn't seem to be honoring globs assigned to `clean_urls`:

```json
{
  "clean_urls": ["/app**", "!/components**"]
}
```

When using an array instead of true/false, all paths continue to be rewritten.

**Comment by scottcorgan** [comment]
@fastdivision can you try putting the negated components glob before the app glob?

I think it parses them in order.

**Comment by fastdivision** [comment]
@scottcorgan I tested a variety of path arrays and none appear to be working. Can you replicate?

**Comment by scottcorgan** [comment]
@fastdivision the nature of globs and how they're matched require that if you want to touch all files in a directory, you need the slash, such as follows: 

```json
{
  "clean_urls": ["/app/**", "!/components/**"]
}
```

**Comment by fastdivision** [comment]
@scottcorgan Makes sense, I need to update the documentation examples to include the slash. Keeping open to investigate multiple exclude patterns as discussed.

**Comment by scottcorgan** [comment]
Seems to be a glob styling issue and not so much a superstatic issue. 

See https://github.com/isaacs/node-glob#glob-primer for information on constructing file globs
