### ISSUE TITLE
Listening on UNIX sockets?

### ISSUE THREAD

**Issue by danopia** [divshot/superstatic#163]
I'm using superstatic to host sites behind nginx. While TCP works, my usecase works better by far with UNIX sockets between nginx and superstatic. For example, superstatic listening on `/tmp/sites/<id>.sock` and nginx connecting to that socket to proxy requests.

Is this possible now? Can support be added?

**Comment by scottcorgan** [comment]
Are you using Superstatic as a middleware or a standalone server?

**Comment by danopia** [comment]
Standalone, like so (in my supervisor config):
```[program:backend1]
user=web
directory=/home/web/sites/backend1
command=/usr/bin/env superstatic --port <what goes here?>```

...and then just a simple nginx proxy routing to these standalone backends

**Comment by scottcorgan** [comment]
You may look into using Superstatic as a middleware with something like Connect, Express, or raw the http module, and then provide a way for those types of services to listen on a unix socket (if that's even possible).

You also may be able to write and adapter that uses superstatic middleware and starts a connection to a socket as you wish. It would be an interesting idea.

This type of feature seems to be out of scope of the Superstatic project.

**Comment by danopia** [comment]
Oh actually, I just realized this already works. You can literally just use `ss --port /tmp/ss.sock` and then it listens correctly on the unix socket. The output is wonky though: `Visit http://localhost:/tmp/ss.sock to view your app.`

This can be made more clear in docs or something, up to you. I'm just happy it works
