### ISSUE TITLE
Custom error page not loading properly

### ISSUE THREAD

**Issue by shamoons** [divshot/superstatic#164]
I am running from CLI via `./node_modules/.bin/superstatic ./dist --port 8080 --no-cache`

My `superstation.json` (which is in my root) has:
```
{
  "errorPage": "./dist/index.html"
}
```

However, the standard `error.html` gets displayed on error.

**Comment by scottcorgan** [comment]
@shamoons try removing the `dist` from the path. It is relative to your root directory.

**Comment by shamoons** [comment]
My `index.html` page is in the `dist/index.html`. So is it relative to where I am running the command from or from where I specify it to serve from?

**Comment by scottcorgan** [comment]
Relative to the root. So ./dist is the root in your case, so you can drop it from the path to your error page.

**Comment by scottcorgan** [comment]
@shamoons I'm going to close this as a non-issue. Please let me know if you need any more help.

**Comment by shamoons** [comment]
Where should my `superstation.json` file be? In my root or in `dist`?

**Comment by kevinchau** [comment]
@shamoons if your configured root directory is ./dist, then place it in root.
