### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by okvic77** [divshot/superstatic#166]
Option for be more express-middleware.

Use/merge the ``res.locals`` object to /__/env.(js|json). Like the express variables ``res.locals`` to be/merge the env configuration.

Thanks.

**Comment by scottcorgan** [comment]
Do you have any code samples to clarify what you mean?

**Comment by okvic77** [comment]
http://expressjs.com/4x/api.html#app.locals
https://github.com/strongloop/express/blob/master/lib/response.js#L917-L939

The app.locals from express v4 are used when you ``res.render()`` a response.
```
app.get('/', function (req, res) {
  res.render('index');
});
```
And the arguments from the render engine use the ``locals``.

The global variables and the response (temporary, each request) are saves in ``res.locals`` and ``res.app.locals``. It'll be pretty cool that these variables where taken to the env variables of superstatic. So we can use the path ``/__/env.json`` for getting this variables.

**Comment by scottcorgan** [comment]
One of the main goals of Superstatic was to be framework agnostic. That's one of the main reasons that we don't use any Express helpers internally.

It shouldn't be too difficult to wire something like this up by wrapper Superstatic in a middleware of it's own,
