### ISSUE TITLE
error_page in config not rendering

### ISSUE THREAD

**Issue by thenoelforte** [divshot/superstatic#170]
I'm using the Superstatic Middleware so I can have vhosts on my app. I've set the following in a `.js` file that is running the node server:

```
main.use(superstatic({
	config: {
		root: './',
		routes: {
			"**": 'index.html'
		},
		error_page: '404.html'
	},
	cwd:	 '/home/noel/sites/www/main'
}));
```

For some reason, if I navigate to say for example `mysite.com/this-should-be-an-error`, I still get served the index page, and don't know why. It's almost like the JSON just isn't working.

Any help in resolving this would be appreciated.

**Comment by thenoelforte** [comment]
Nevermind, I just removed the `routes` option of the `config` and things started working as expected. I had a feeling I was making a catch-all.

**Comment by scottcorgan** [comment]
Does it work if you remove the `cwd` option?
