### ISSUE TITLE
support etags

### ISSUE THREAD

**Issue by scottcorgan** [divshot/superstatic#41]

**Comment by djindjic** [comment]
are etags suported now? I cant find in docs

**Comment by scottcorgan** [comment]
Documentation will be updated soon. Etags have basic support for Superstatic, but are yet to be pushed into Divshot hosting.

We are working over the next week or 2 to get Superstatic 2.0 into the Divshot servers.

**Comment by djindjic** [comment]
good news, thanks! could you reopen this issue to allow us to follow progress?

thanks

**Comment by scottcorgan** [comment]
Sure. I'll respond here when there's more to update.

**Comment by scottcorgan** [comment]
Etags will be turned on for all requests. No need to configure.

**Comment by scottcorgan** [comment]
Shipped as `2.1.0` to NPM!

**Comment by djindjic** [comment]
Hey, thanks!

**Comment by linstula** [comment]
@scottcorgan any idea when Divshot will be running `2.1.0`?

**Comment by scottcorgan** [comment]
@linstula That's what I'm on right now. The goal is push this out next week or the following week.

**Comment by mmccroskey** [comment]
@scottcorgan Wondering whether this has been pushed live to Divshot yet?
